(()=>{'use strict';
const K='carsv4',OLD='carsv3',SEATS=['front','mid1','mid2','mid3','back1','back2'],MID=['mid1','mid2','mid3'],BACK=['back1','back2'];
const N={front:'קדמי',mid1:'אמצע שמאל',mid2:'אמצע אמצע',mid3:'אמצע ימין',back1:'אחורי שמאל',back2:'אחורי ימין'},I={m:'👦',f:'👧',n:'🧒'};
let S={version:4,parents:['הורה 1','הורה 2'],children:[],trips:[]},D={type:'short',parents:[],children:[],seats:{}},activeSeat=null,fixedId=null,deferredPrompt=null;
const $=id=>document.getElementById(id),mk=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x},uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
function normalize(v){const x={version:4,parents:['הורה 1','הורה 2'],children:[],trips:[]};if(!v||typeof v!=='object')return x;x.parents=Array.isArray(v.parents)?v.parents.slice(0,2).map(String):x.parents;while(x.parents.length<2)x.parents.push(`הורה ${x.parents.length+1}`);x.children=Array.isArray(v.children)?v.children.filter(Boolean).map(c=>({id:String(c.id||uid()),name:String(c.name||'').trim(),gender:I[c.gender]?c.gender:'n',fixedSeat:SEATS.includes(c.fixedSeat)?c.fixedSeat:null})).filter(c=>c.name):[];x.trips=Array.isArray(v.trips)?v.trips.slice(0,300):[];return x}
function migrate(o){const x={version:4,parents:Array.isArray(o.parents)?o.parents.slice(0,2).map(String):['הורה 1','הורה 2'],children:[],trips:[]},map=new Map();x.children=(o.children||[]).map(c=>{const q={id:uid(),name:String(c.name||'').trim(),gender:I[c.gender]?c.gender:'n',fixedSeat:SEATS.includes(c.fixedSeat)?c.fixedSeat:null};map.set(q.name,q.id);return q}).filter(c=>c.name);x.trips=(o.trips||[]).slice(0,300).map(t=>{const seats={};Object.entries(t.seats||{}).forEach(([s,n])=>{const id=map.get(n);if(SEATS.includes(s)&&id)seats[s]=id});const d=new Date(`${t.date||''} ${t.time||''}`);return{id:String(t.id||uid()),createdAt:Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString(),type:t.type==='long'?'long':'short',parentNames:(t.parents||[]).map(i=>x.parents[i]).filter(Boolean),children:(t.children||[]).map(n=>map.get(n)).filter(Boolean),childNames:Object.fromEntries(x.children.map(c=>[c.id,c.name])),seats}});return x}
function load(){try{const cur=localStorage.getItem(K);if(cur){S=normalize(JSON.parse(cur));return}const old=localStorage.getItem(OLD);if(old){S=migrate(JSON.parse(old));save()}}catch(e){console.error(e);alert('הנתונים המקומיים נפגמו ולא נטענו. אפשר לייבא גיבוי מההגדרות.')}}
function save(){try{localStorage.setItem(K,JSON.stringify(S))}catch(e){console.error(e);alert('השמירה נכשלה. מומלץ לייצא גיבוי.');throw e}}
const child=id=>S.children.find(c=>c.id===id),name=(id,t)=>child(id)?.name||t?.childNames?.[id]||'ילד/ה שנמחק/ה',zone=s=>s==='front'?'front':String(s).startsWith('back')?'back':'mid',seatOf=(t,id)=>Object.keys(t.seats||{}).find(s=>t.seats[s]===id);
function stats(id,type,z){const ts=S.trips.filter(t=>t.type===type&&t.children?.includes(id));let count=0,since=Number.MAX_SAFE_INTEGER;ts.forEach((t,i)=>{if(zone(seatOf(t,id))===z){count++;if(since===Number.MAX_SAFE_INTEGER)since=i}});return{count,since}}
function rank(ids,type,z){return[...ids].sort((a,b)=>{const x=stats(a,type,z),y=stats(b,type,z);return x.count-y.count||y.since-x.since||name(a).localeCompare(name(b),'he')})}
function fixedError(ids){const used=new Map();for(const id of ids){const c=child(id);if(!c?.fixedSeat)continue;if(used.has(c.fixedSeat))return`המושב ${N[c.fixedSeat]} מוגדר גם ל${name(used.get(c.fixedSeat))} וגם ל${c.name}.`;used.set(c.fixedSeat,id)}if(used.has('front')&&D.parents.length!==1)return'מושב קדמי קבוע לילד זמין רק כאשר נבחר הורה אחד בדיוק.';return null}
const capacity=()=>5+(D.parents.length===1?1:0);
function generate(){if(!D.children.length)return alert('יש לבחור לפחות ילד/ה אחד/ת.');if(D.children.length>capacity())return alert(`נבחרו ${D.children.length} ילדים, אך יש רק ${capacity()} מושבים זמינים בהרכב הזה.`);const err=fixedError(D.children);if(err)return alert(err);const seats={},fixed=new Set();D.children.forEach(id=>{const c=child(id);if(c?.fixedSeat){seats[c.fixedSeat]=id;fixed.add(id)}});let rem=D.children.filter(id=>!fixed.has(id));if(D.parents.length===1&&!seats.front&&rem.length){const id=rank(rem,D.type,'front')[0];seats.front=id;rem=rem.filter(x=>x!==id)}const fm=MID.filter(s=>!seats[s]),fb=BACK.filter(s=>!seats[s]),need=Math.max(0,rem.length-fm.length),backs=rank(rem,D.type,'back').slice(0,need);backs.forEach((id,i)=>seats[fb[i]]=id);rem=rem.filter(id=>!backs.includes(id));rem.forEach((id,i)=>seats[fm[i]]=id);D.seats=seats;const v=validate();if(v)return alert(v);renderCar();$('setupView').hidden=true;$('assignmentView').hidden=false;$('assignmentMessage').textContent='סידור המושבים מוכן. אפשר ללחוץ על מושב ולערוך ידנית.'}
function validate(){const a=Object.values(D.seats),sel=new Set(D.children);if(a.length!==new Set(a).size)return'אותו ילד שובץ ביותר ממושב אחד.';if(a.some(id=>!sel.has(id)))return'קיים במושבים ילד שלא נבחר לנסיעה.';if(a.length!==D.children.length)return'לא כל הילדים שובצו למושב.';if(D.parents.length!==1&&D.seats.front)return'המושב הקדמי אינו זמין בהרכב ההורים הנוכחי.';for(const id of D.children){const f=child(id)?.fixedSeat;if(f&&D.seats[f]!==id)return`${name(id)} חייב/ת לשבת במושב הקבוע: ${N[f]}.`}return null}
function saveTrip(){const v=validate();if(v)return alert(v);S.trips.unshift({id:uid(),createdAt:new Date().toISOString(),type:D.type,parentNames:D.parents.map(i=>S.parents[i]),children:[...D.children],childNames:Object.fromEntries(D.children.map(id=>[id,name(id)])),seats:{...D.seats}});S.trips=S.trips.slice(0,300);save();D={type:D.type,parents:[...D.parents],children:[],seats:{}};$('assignmentView').hidden=true;$('setupView').hidden=false;renderAll();alert('הנסיעה נשמרה.')}
function renderTrip(){ $('tripCounter').textContent=`${S.trips.length} נסיעות`;$('shortBtn').classList.toggle('selected',D.type==='short');$('longBtn').classList.toggle('selected',D.type==='long');$('parentsGrid').replaceChildren(...S.parents.map((n,i)=>{const b=mk('button','choice',n||`הורה ${i+1}`);b.classList.toggle('selected',D.parents.includes(i));b.onclick=()=>{D.parents=D.parents.includes(i)?D.parents.filter(x=>x!==i):[...D.parents,i];renderTrip()};return b}));const list=$('childrenList');if(!S.children.length){list.replaceChildren(mk('div','empty','אין ילדים. יש להוסיף ילדים בהגדרות.'));return}list.replaceChildren(...S.children.map(c=>{const r=mk('div','row'),b=mk('button','row-main');b.type='button';b.append(mk('span','avatar',I[c.gender]),mk('span','',c.name),mk('span',`check ${D.children.includes(c.id)?'on':''}`,D.children.includes(c.id)?'✓':'○'));b.onclick=()=>{D.children=D.children.includes(c.id)?D.children.filter(id=>id!==c.id):[...D.children,c.id];renderTrip()};r.append(b);return r}))}
function renderCar(){document.querySelectorAll('[data-seat]').forEach(b=>{const s=b.dataset.seat,id=D.seats[s];b.replaceChildren();b.className='seat';if(!id){b.textContent='+';return}const c=child(id);b.classList.add('occupied');if(c?.fixedSeat===s)b.classList.add('fixed');b.append(mk('span','',I[c?.gender||'n']),mk('span','',name(id)))})}
function assignDialog(seat){activeSeat=seat;$('assignTitle').textContent=`בחר ילד/ה — ${N[seat]}`;$('assignOptions').replaceChildren(...D.children.map(id=>{const c=child(id),r=mk('div','row'),b=mk('button','row-main');b.type='button';b.append(mk('span','avatar',I[c?.gender||'n']),mk('span','',name(id)));b.onclick=()=>{if(c?.fixedSeat&&c.fixedSeat!==seat)return alert(`${c.name} מוגדר/ת למושב קבוע: ${N[c.fixedSeat]}.`);const owner=S.children.find(x=>x.fixedSeat===seat&&D.children.includes(x.id));if(owner&&owner.id!==id)return alert(`המושב שמור ל${owner.name}.`);Object.keys(D.seats).forEach(s=>{if(D.seats[s]===id)delete D.seats[s]});D.seats[seat]=id;$('assignDialog').close();renderCar()};r.append(b);return r}));$('assignDialog').showModal()}
function renderQueues(){['front','back'].forEach(z=>['short','long'].forEach(type=>{const box=$(`q-${z}-${type}`),ids=S.children.filter(c=>!c.fixedSeat).map(c=>c.id);if(!ids.length){box.replaceChildren(mk('div','empty','אין ילדים בתורנות.'));return}box.replaceChildren(...rank(ids,type,z).map((id,i)=>{const r=mk('div','row'),s=stats(id,type,z);r.append(mk('span','queue-rank',String(i+1)),mk('span','avatar',I[child(id)?.gender||'n']),mk('span','',`${name(id)} · ${s.count} פעמים`));return r}))}))}
function renderHistory(){const box=$('stats');box.replaceChildren(stat('סה״כ נסיעות',S.trips.length),stat('עם ילד בקדמי',S.trips.filter(t=>t.seats?.front).length));const list=$('historyList');if(!S.trips.length){list.replaceChildren(mk('div','empty','אין נסיעות עדיין.'));return}list.replaceChildren(...S.trips.slice(0,30).map(t=>{const r=mk('div','row'),d=new Date(t.createdAt),names=(t.children||[]).map(id=>name(id,t)).join(', '),front=t.seats?.front?` · קדמי: ${name(t.seats.front,t)}`:'';r.append(mk('div','',d.toLocaleDateString('he-IL')),mk('div','',`${names||'—'}${front}`),mk('div','hint',t.type==='long'?'ארוכה':'קצרה'));return r}))}
function renderSettings(){ $('parent0').value=S.parents[0]||'';$('parent1').value=S.parents[1]||'';const box=$('childrenSettings');if(!S.children.length){box.replaceChildren(mk('div','empty','אין ילדים עדיין.'));return}box.replaceChildren(...S.children.map(c=>{const r=mk('div','row'),main=mk('div','');main.append(mk('strong','',`${I[c.gender]} ${c.name}`));if(c.fixedSeat)main.append(mk('div','fixed-label',`📌 ${N[c.fixedSeat]}`));const e=mk('button','small-btn','ערוך'),f=mk('button','small-btn','מושב קבוע'),d=mk('button','small-btn','מחק');e.onclick=()=>edit(c.id);f.onclick=()=>fixedDialog(c.id);d.onclick=()=>remove(c.id);r.append(main,e,f,d);return r}))}
function edit(id){const c=child(id),v=prompt('שם חדש:',c.name);if(v===null)return;const n=v.trim();if(!n)return alert('השם אינו יכול להיות ריק.');if(S.children.some(x=>x.id!==id&&x.name.toLocaleLowerCase('he')===n.toLocaleLowerCase('he')))return alert('כבר קיים ילד בשם הזה.');c.name=n;save();renderAll()}
function remove(id){const c=child(id);if(!confirm(`למחוק את ${c.name}? ההיסטוריה הישנה תישמר.`))return;S.children=S.children.filter(x=>x.id!==id);D.children=D.children.filter(x=>x!==id);Object.keys(D.seats).forEach(s=>{if(D.seats[s]===id)delete D.seats[s]});save();renderAll()}
function add(){const n=$('newChildName').value.trim();if(!n)return alert('יש להזין שם.');if(S.children.some(c=>c.name.toLocaleLowerCase('he')===n.toLocaleLowerCase('he')))return alert('כבר קיים ילד בשם הזה.');S.children.push({id:uid(),name:n,gender:$('newChildGender').value,fixedSeat:null});$('newChildName').value='';save();renderAll()}
function fixedDialog(id){fixedId=id;const c=child(id);$('fixedTitle').textContent=`מושב קבוע — ${c.name}`;$('fixedOptions').replaceChildren(...SEATS.map(s=>{const owner=S.children.find(x=>x.id!==id&&x.fixedSeat===s),b=mk('button','choice',owner?`${N[s]} — תפוס`:N[s]);b.type='button';b.disabled=!!owner;b.classList.toggle('selected',c.fixedSeat===s);b.onclick=()=>{c.fixedSeat=s;save();$('fixedDialog').close();renderAll()};return b}));$('fixedDialog').showModal()}
function backup(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`carseats-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function restore(file){try{const x=normalize(JSON.parse(await file.text()));if(!confirm(`לייבא ${x.children.length} ילדים ו-${x.trips.length} נסיעות? הנתונים הנוכחיים יוחלפו.`))return;S=x;save();D={type:'short',parents:[],children:[],seats:{}};renderAll()}catch(e){console.error(e);alert('קובץ הגיבוי אינו תקין.')}finally{$('importInput').value=''}}
function showTab(n){document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==`tab-${n}`);document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===n));if(n==='queue')renderQueues();if(n==='history')renderHistory();if(n==='settings')renderSettings()}
function stat(label,v){const x=mk('div','stat');x.append(mk('span','',label),mk('strong','',String(v)));return x}function renderAll(){renderTrip();renderQueues();renderHistory();renderSettings()}
function bind(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-trip-type]').forEach(b=>b.onclick=()=>{D.type=b.dataset.tripType;renderTrip()});document.querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>assignDialog(b.dataset.seat));$('generateBtn').onclick=generate;$('saveTripBtn').onclick=saveTrip;$('editTripBtn').onclick=()=>{$('assignmentView').hidden=true;$('setupView').hidden=false};$('clearSeatBtn').onclick=()=>{const id=D.seats[activeSeat];if(id&&child(id)?.fixedSeat===activeSeat)return alert('אי אפשר להסיר ילד מהמושב הקבוע שלו.');delete D.seats[activeSeat];$('assignDialog').close();renderCar()};$('parent0').onchange=e=>{S.parents[0]=e.target.value.trim()||'הורה 1';save();renderAll()};$('parent1').onchange=e=>{S.parents[1]=e.target.value.trim()||'הורה 2';save();renderAll()};$('addChildBtn').onclick=add;$('newChildName').onkeydown=e=>{if(e.key==='Enter')add()};$('removeFixedBtn').onclick=()=>{child(fixedId).fixedSeat=null;save();$('fixedDialog').close();renderAll()};$('exportBtn').onclick=backup;$('importInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0])};$('clearHistoryBtn').onclick=()=>{if(confirm('למחוק את כל היסטוריית הנסיעות?')){S.trips=[];save();renderAll()}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=mk('button','primary','התקן כאפליקציה');b.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBanner').replaceChildren()};$('installBanner').replaceChildren(b)})}
load();bind();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);
})();